### ISSUE TITLE
bucket name, https, static website hosting? 

### ISSUE THREAD

**Issue by luntzel** [poise/citadel#17]
I had to do some arguably strange things to get this to (sorta) work:

I have node['citadel']['bucket'] set to "com.example.vcat.secrets"

I have this in the recipe:

```ruby 
file '/etc/rootonly/file-we-want' do
  owner 'root'
  group 'root'
  mode '600'
  content citadel['file-we-want']
end
```

I have the policy on the bucket set to this:

```json
{
	"Version": "2008-10-17",
	"Id": "vcat",
	"Statement": [
		{
			"Sid": "vcat-secrets",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::0000000000:role/vcat"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::com.example.vcat.secrets/*"
		}
	]
}
```

Citadel generates a url "https://com.example.vcat.secrets.s3.amazonaws.com/file-we-want" but the chef-client run fails because the hostname does not match the certificate. The README states

>While citadel uses HTTPS, Chef does not verify certificates by default. You can enable verification by adding ssl_verify_mode :verify_peer to your client.rb.

I don't believe that is the case, anymore. I changed libraries/s3_file.rb to use http as a test, ~~but that only works if I enable "static website hosting" on the bucket in question and is lame anyway~~. What am I missing here? Thank you in advance. 

Chef: 12.2.1
Ubuntu: 14.04
Enterprise Hosted Chef
Citadel version '1.0.2'

**Comment by luntzel** [comment]
Is this thing on? I get the feeling that it's been abandoned...

**Comment by mjallday** [comment]
I can't speak to the maintenance of this library, but for the bucket name, can you work around this by using the AWS url e.g. "https://s3-us-east-1.amazonaws.com/com.example.vcat.secrets/file-we-want"?

**Comment by luntzel** [comment]
@mjallday It's an interesting idea. This needs to get tweaked to make that work: 

https://github.com/poise/citadel/blob/master/libraries/s3_file.rb#L54

I'll see if I can get that rolling.

**Comment by luntzel** [comment]
So I've got this down to chef puking on the mismatch on the SSL certificate. I set 

`ssl_verify_mode ":verify_none"`

in /etc/chef/client.rb and it worked fine. This doesn't seem like a great solution...thoughts?

**Comment by luntzel** [comment]
Maybe an attribute to switch off SSL verification for Chef::HTTP?

**Comment by luntzel** [comment]
Strike that. It does not work with `ssl_verify_mode ":verify_none"` in client.rb. (I had http in the cookbook)

seems like using the https url is not going to ever work, considering how chef forces the use of verify_peer.

**Comment by coderanger** [comment]
So the root issue with this is that HTTPS verification doesn't work with periods in the bucket name. S3 officially recommends against using bucket names like this because of that. the foo.s3.amazonaws.com DNS wildcard correctly dispatches to the region the bucket is in I think, whereas s3.amazonaws.com/foo does not (which is why you need s3-<region>.amazonaws.com/foo). Other than another config option, there isn't a great solution to this other than "never use periods in bucket names unless you are planning to CNAME them".

**Comment by coderanger** [comment]
Fixed in master.
