### ISSUE TITLE
newline in key value due to the citadel method

### ISSUE THREAD

**Issue by domofactor** [poise/citadel#20]
hey guys,

thanks for writing this, its a great alternative to data-bags! 

I'm seeing some wierdness at converge time though with the citadel method. It seems to be appending a newline to the value in my keyfile. in my test, instead of seeing the string ```supersecretsomestring``` I'm getting ```supersecret\nsomestring```. Thanks!

example recipe.
```
puts "#{citadel["#{cookbook_name}/secret.pem"]}" + "somestring"
```

This is what my converge looks like in test-kitchen:
```
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-base>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-base>
       Starting Chef Client, version 12.4.1
       [2015-09-09T11:50:00+09:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["common::_test_citadel"]
       Synchronizing Cookbooks:
         - common
         - chef-client
         - apt
         - ntp
         - resolver
         - citadel
         - cron
         - logrotate
         - windows
         - chef_handler
       Compiling Cookbooks...
       Digest::Digest is deprecated; use Digest
       supersecret
       somestring
       Converging 0 resources
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 2.46349934 seconds
       Finished converging <default-base> (0m11.37s).
```

**Comment by domofactor** [comment]
its worth noting that i've made sure there are no newlines in the secret.pem file itself in S3.

**Comment by coderanger** [comment]
Hmm, how are you verifying there is no newline in the file on S3? I don't see anything in the code that would risk a rogue character being added, just a straight HTTP GET call :-/

**Comment by domofactor** [comment]
I just echo'ed a sample string into a new file and cat it.
```
falcon@nest:~$ echo 'supersecret' > secret.pem
falcon@nest:~$ cat secret.pem
supersecret
```

I totally agree with you, code wise it doesn't look like any newlines are being added, but it seems to me that S3 itself is returning the new line for some reason. 

Maybe i'm just nuts? lol i'll try to do some more digging shortly.

**Comment by mjallday** [comment]
@domofactor try `echo -n 'supersecret'`

`man echo` 
...
> `-n`    Do not print the trailing newline character

**Comment by coderanger** [comment]
Closing this as not reproducible.

**Comment by nullck** [comment]
@coderanger I can reproduce this:

try to create a template like this:

template "/tmp/test" do
  source "test.erb"
  owner "root"
  group "root"
  mode 0660
  variables({
    :password => node['cookbook_teste]['password']
    })
end

will generate this:

cat /tmp/test
password=P455word

if I create a file in my s3 bucket with this content:
P455word

and modify my recipe to use citadel like this:

template "/tmp/test_citadel" do
  source "test.erb"
  owner "root"
  group "root"
  mode 0660
  variables({
    :password => citadel['keys_secrets/password']
    })
end

The result will be a /tmp/test_citadel with this content, including a breakline
P455word

diff between files /tmp/test /tmp/test_citadel

12:04:13 ip-10-0-54-20:~# diff /tmp/teste /tmp/teste_citadel
2a3
>
