### ISSUE TITLE
Create ChefSpec

### ISSUE THREAD

**Issue by j-carl** [poise/citadel#26]
I ran into some problems when I create some testing for my recipe with `file` resource and citadel. I was able to set some fake credentials in my spec file, like this:

    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new do |node, server|
        node.set['citadel']['access_key_id'] = 'unittest'
        node.set['citadel']['secret_access_key'] = 'unittest'

        server.update_node(node)
      end
    end

    it 'download from S3' do
      expect(chef_run).to create_file('/tmp/s3_file.txt')
    end
    ...

But citadel still tries to reach out to S3 and the test fails and any subsequent tests.

It would be great if you could provide a ChefSpec, so unit testing would work.

Thx

**Comment by coderanger** [comment]
What you have should work. Try logging the value of `node['citadel']['access_key_id']` inside your test recipe?

**Comment by j-carl** [comment]
Sorry if the thing I'm asking for wasn't quite clear. I'm really would love to have ChefSpec (maybe with an new matcher like `create_file_citadel()`), where you stub your class `Citadel`, so no connection to S3 is needed during unit testing.

**Comment by coderanger** [comment]
Citadel isn't a resource so it doesn't interact with ChefSpec like that.

**Comment by j-carl** [comment]
I wasn't aware of that.

I know that integration test (with kitchen) will work, but for my use case this is unfortunately not possible. So I would really appreciate it, when there is way to make unit testing working with ChefSpec.

**Comment by coderanger** [comment]
It already works fine, `allow_any_instance_of(Chef::Recipe).to receive(:citadel).and_return('foo' => 'bar')`. Tweak as needed. Standard RSpec mocking stuffs, no special sauce needed.
