### ISSUE TITLE
newline in key value due to the citadel method ref issue #20

### ISSUE THREAD

**Issue by nullck** [poise/citadel#27]
@coderanger I saw the issue #20 is closed because isn't possible to reproduce the problem, that the citadel adding a breakline when we create a template using them, but I can reproduce the behavior:

try to create a template like this:

template "/tmp/test" do
source "test.erb"
owner "root"
group "root"
mode 0660
variables({
:password => node['cookbook_teste]['password']
})
end

will generate this:

cat /tmp/test
password=P455word

if I create a file in my s3 bucket with this content:
P455word

and modify my recipe to use citadel like this:

template "/tmp/test_citadel" do
source "test.erb"
owner "root"
group "root"
mode 0660
variables({
:password => citadel['keys_secrets/password']
})
end

The result will be a /tmp/test_citadel with this content, including a breakline
P455word

diff between files /tmp/test /tmp/test_citadel

12:04:13 ip-10-0-54-20:~# diff /tmp/teste /tmp/teste_citadel
2a3
>

**Comment by coderanger** [comment]
There is a very very high chance this means there was a newline in the file you uploaded to S3. Which is what I said last time. Next time please run through the same debugging steps before opening a new issue. Regardless you can fix this on the Ruby side with a `.strip` method call.

**Comment by nullck** [comment]
http://stackoverflow.com/questions/23193813/how-does-gets-and-gets-chomp-in-ruby-work

man please read this.

"gets lets the user input a line and returns it as a value to your program. This value includes the trailing line break. If you then call chomp on that value, this line break is cut off. So no, what you have there is incorrect, it should rather be:

gets gets a line of text, including a line break at the end.
This is the user input
gets returns that line of text as a string value.
Calling chomp on that value removes the line break"

In your case:

citadel/files/halite_gem/citadel/s3.rb

 76       begin
 77         Chef::HTTP.new("https://#{hostname}").get("#{bucket}/#{path}", headers)**.chomp**

I made it and VOILA!!
Please fix it!

**Comment by coderanger** [comment]
I'm saying that belongs in _your_ code. `citadel['keys_secrets/password'].strip` (or `citadel['keys_secrets/password'].chomp` if you prefer, but `strip` is probably safer).

**Comment by coderanger** [comment]
Alternatively fix your uploaded data on S3 to not have a newline.

**Comment by dragon788** [comment]
We ran into this after upgrading from Chef 13.2.20 to Chef 13.6.4 and updating the Hashicorp Vault gem to 1.1.0 from a previous version. Recipes that were working fine suddenly started failing with `header field value cannnot include CR/LF`. Using `chomp` as mentioned fixes the issues with the files in S3 having a trailing newline (which many if not all editors on *nix platforms tend to add unless overridden).
