### ISSUE TITLE
Chef::Exceptions::CookbookNotFound

### ISSUE THREAD

**Issue by ellier** [poise/citadel#32]
I'm trying to include this cookbook include_recipe 'citadel' and getting Chef::Exceptions::CookbookNotFound.

I already included it in metadata.rb and Berksfile, and installed it with berks.

I'd really appreciate some guidance here as the documentation is not clear to me. Thanks.

**Comment by ellier** [comment]
In case someone comes here with the same problem, this is how I was able to resolve my issues using Citadel.

First: Do not include the citadel cookbook in your recipe. You only need to list it as a dependency in your metadata.rb file and in your Berksfile

Second: If you start getting 'undefined method `citadel' for Chef::Resource::File' errors, delete metadata.json file and Berkfile.lock. Then run berks install and run kitchen converge if using kitchen

Last: If you continue to have issues, ask for help in the #chef irc channel. The guys there helped me resolve this

**Comment by coderanger** [comment]
Resolved in IRC as per ^^

**Comment by coderanger** [comment]
The specific issue with that you don't need the `include_recipe` and that an out of date `metadata.json` overrides the `metadata.rb`.
