### ISSUE TITLE
S3 best practice documentation

### ISSUE THREAD

**Issue by eprothro** [poise/citadel#33]
It's clear after a little research that the limitation of a single IAM role per instance is a key factor in the design of how to use citadel effectively.

It would be very helpful if the README gave an example of a recommended S3 structure. This seems like something that any existing user has had to think about and/or fight with, and passing that knowledge on to new adopters like myself would help a lot.

I'm happy to do the documentation itself if that helps.

**Comment by coderanger** [comment]
I mean https://github.com/poise/citadel#iam-policy basically covers that. The one-role rule just means you need to make roles for every combination of access masks, usually best handled in a tool like Terraform or Sparkleformation or Troposphere.

**Comment by eprothro** [comment]
Sorry, I was talking about the structure of S3 buckets/files.

E.g. when managing different passwords for sandbox and prod database passwords

/app-sandbox-secrets/some-database/password
and 
/app-prod-secrets/some-database/password

or something else.

I think how to manage some shared and some unique secrets is alluded to a few places in the readme, but a concrete example would be very helpful.

**Comment by coderanger** [comment]
So it's mentioned right below the IAM example, I recommend grouping secrets into named sets and making each of those sets a folder. Some sets (most, probably) will contain exactly one secret, but some might have more. It's really up to you though.

**Comment by eprothro** [comment]
Would you accept a PR for filling that section out a little bit? In trying to onboard, I had two outstanding questions that I would imagine others have had as well, both of which seem easy to avoid with a bit of documentation.

* How exactly am I going to manage groups of secrets and some shared secrets with respect to S3 object hierarchy.
* What about availability? S3 bucket seems like a SPOF.

**Comment by coderanger** [comment]
> On Jun 2, 2017, at 7:58 AM, Evan Prothro <notifications@github.com> wrote:
> 
> Would you accept a PR for filling that section out a little bit? In trying to onboard, I had two outstanding questions that I would imagine others have had as well, both of which seem easy to avoid with a bit of documentation.
> 
> 	• How exactly am I going to manage groups of secrets and some shared secrets with respect to S3 object hierarchy.

I don't really want to voice a more specific opinion on this given the variables involved. You need to think it through yourself.

> 	• What about availability? S3 bucket seems like a SPOF.

If you're running Amazon stuff to start with, you've long-since accepted S3 as a failure mode. We all saw what happened when it went down, not really something you can plan for other than going multi-region or multi-cloud.

--Noah

**Comment by coderanger** [comment]
Going to close this out.

**Comment by coderanger** [comment]
And re: cross-region replication, that's both outside the scope of this cookbook and not actually helpful unless your AWS footprint is also cross-region (which most are not).

**Comment by eprothro** [comment]
👍 thanks again for the time and comments.
