### ISSUE TITLE
Issues with Citadel::S3.get

### ISSUE THREAD

**Issue by willfish** [poise/citadel#37]
I've been debugging why the `Citadel::S3.get` method returns nil for me despite have all of the same inputs as another version of citadel (ignore which version, it's a fork we created to speed up development internally).

I did some hacking around in chef-shell against 1.1.0 in the chef supermarket and found that if I change the way the request is constructed the requests work as before (in our forked implementation):

Working implementation:
```ruby
Chef::HTTP.new("https://#{bucket}.s3.amazonaws.com").get(path, headers)
```

Broken implementation
```ruby
Chef::HTTP.new("https://#{hostname}").get("#{bucket}/#{path}", headers)
```

With the broken implementation I get:
```ruby
chef:recipe (12.19.36)> Citadel::S3.get(bucket: @bucket, path: key, region: @region, **@credentials)
 => nil
```

When I monkey patch the Citadel::S3.get method with the correct implementation I get:
```ruby
chef:recipe (12.19.36)> Citadel::S3.get(bucket: @bucket, path: key, region: @region, **@credentials)
 => "{}\n"
```

See:
https://github.com/poise/citadel/blob/master/lib/citadel/s3.rb#L77

Ideally, we'd move to the working implementation and bump the patch version of this cookbook so that everybody can use it.

Should be a relatively small amount of work to update the specs and change the line.

**Comment by coderanger** [comment]
This probably means your bucket isn’t in us-east1 and you didn’t correctly set the region/hostname. Using the bucket hostname as you show will fail on any bucket with a period in the name.

**Comment by willfish** [comment]
Thanks for the response. I'll check out my setup and update here soon.

**Comment by coderanger** [comment]
The error messages could probably stand to be better :) Long ago when I first wrote this, Amazon was more forgiving about automatically redirecting you to the right host, but these days I think they just fail the request if you ask for a bucket in the wrong region.
